import type { Metadata } from "next";
import { Inter, Sulphur_Point } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const sulphur = Sulphur_Point({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-sulphur" });

export const metadata: Metadata = {
  title: "Health Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} ${sulphur.variable} bg-[#CBD3DE]`}>{children}</body>
    </html>
  );
}
